USE QuanLyGiaoVu_DB

--9.
GO
CREATE TRIGGER CHECK_TRGLOP
ON LOP
AFTER INSERT, UPDATE
AS
BEGIN
	DECLARE @TRGLOP char(5),		
			@MALOP1 char(3),		
			@MALOP2 char(3)

	SELECT @TRGLOP = TRGLOP, @MALOP1 = MALOP FROM INSERTED
	SELECT @MALOP2 = MALOP FROM HOCVIEN WHERE MAHV = @TRGLOP
	IF (@MALOP1 <> @MALOP2)
	BEGIN
		PRINT N'Lớp trưởng của một lớp phải là học viên của lớp đó!'
		ROLLBACK TRANSACTION
	END
END

--10.
GO
CREATE TRIGGER CHECK_TRGKHOA
ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @TRGKHOA char(4), @MAKHOA varchar(4), @HOCVI varchar(10)

	SELECT @TRGKHOA = TRGKHOA, @MAKHOA = MAKHOA FROM INSERTED
	SELECT @HOCVI = HOCVI FROM GIAOVIEN WHERE MAGV = @TRGKHOA AND MAKHOA = @MAKHOA

	IF (@HOCVI NOT IN ('TS', 'PTS'))
	BEGIN
		PRINT N'Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”!'
		ROLLBACK TRANSACTION
	END
END

--15.
GO 
CREATE TRIGGER CHECK_NGTHI
ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGTHI smalldatetime, @DENNGAY smalldatetime, @MAHV char(5), @MAMH varchar(10)

	SELECT @NGTHI = NGTHI, @MAHV = MAHV, @MAMH = MAMH FROM INSERTED
	SELECT @DENNGAY = DENNGAY FROM GIANGDAY WHERE MAMH = @MAMH

	IF (@NGTHI < @DENNGAY)
	BEGIN
		PRINT N'  Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này!'
		ROLLBACK TRANSACTION
	END
END

--16.
GO
CREATE TRIGGER CHECK_COUNT_MAMH
ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MALOP char(3), @TONGSOMH int, @HOCKY int, @NAM int

	SELECT @MALOP = MALOP, @HOCKY = HOCKY, @NAM = NAM FROM INSERTED
	SELECT @TONGSOMH = COUNT(MAMH) FROM GIANGDAY WHERE MALOP = @MALOP AND HOCKY = @HOCKY AND NAM = @NAM

	IF (@TONGSOMH > 3)
	BEGIN
		PRINT N'Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn!'
		ROLLBACK TRANSACTION
	END
END

--17.
GO
CREATE TRIGGER CHECK_SISO
ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SISO tinyint, @TONGSOHV tinyint, @MALOP char(3)

	SELECT @SISO = SISO, @MALOP = MALOP FROM INSERTED
	SELECT @TONGSOHV = COUNT(MAHV) FROM HOCVIEN WHERE MALOP = @MALOP

	IF (@TONGSOHV <> @SISO)
	BEGIN
		PRINT N'Sĩ số của một lớp bằng với số lượng học viên thuộc lớp đó!'
		ROLLBACK TRANSACTION
	END
END

--18.
--Kiểm tra MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau (“A”,”A”)
GO
CREATE TRIGGER CHECK_DIEUKIEN
ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAMH varchar(10), @MAMH_TRUOC varchar(10)

	SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC FROM INSERTED

	IF (@MAMH = @MAMH_TRUOC)
	BEGIN
		PRINT N'MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau!'
		ROLLBACK TRANSACTION
	END
END

--Kiểm tra MAMH và MAMH_TRUOC không tồn tại hai bộ (“A”,”B”) và (“B”,”A”)
GO
CREATE TRIGGER CHECK_BOGIONGNHAU
ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(SELECT * FROM DIEUKIEN DK, INSERTED I WHERE DK.MAMH = I.MAMH_TRUOC AND DK.MAMH_TRUOC = I.MAMH)
	BEGIN
		PRINT N'MAMH và MAMH_TRUOC không tồn tại hai bộ!'
		ROLLBACK TRANSACTION
	END
END

--19.
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)

--20.
UPDATE HOCVIEN
SET DIEMTB = (SELECT AVG(DIEM)
			  FROM (SELECT MAHV, MAMH, MAX(LANTHI) MAX_LANTHI 
					FROM KETQUATHI
					GROUP BY MAHV, MAMH) A, KETQUATHI B
			  WHERE A.MAHV = B.MAHV AND MAX_LANTHI = B.LANTHI
			  GROUP BY B.MAHV
			  HAVING B.MAHV = HOCVIEN.MAHV)

--21.
GO
CREATE TRIGGER CHECK_NGAYTHI
ON KETQUATHI
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM KETQUATHI k1
        JOIN KETQUATHI k2 ON k1.MAHV = k2.MAHV AND k1.MAMH = k2.MAMH
        WHERE k2.LANTHI = k1.LANTHI - 1 AND k1.NGTHI <= k2.NGTHI
    )
    BEGIN
        ROLLBACK TRANSACTION
        THROW 50000, 'Ngày thi của lần thi sau phải lớn hơn ngày thi của lần thi trước.', 1
    END
END

--22.
GO
CREATE TRIGGER trg_check_exam_eligibility_class
ON KETQUATHI
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM KETQUATHI kq
        JOIN HOCVIEN hv ON kq.MAHV = hv.MAHV
        JOIN GIANGDAY gd ON hv.MALOP = gd.MALOP AND kq.MAMH = gd.MAMH
        WHERE kq.NGTHI < gd.DENNGAY
    )
    BEGIN
        ROLLBACK TRANSACTION
        THROW 50000, 'Học viên chỉ được thi những môn mà lớp đã học xong.', 1
    END
END

--23.
GO
CREATE TRIGGER trg_check_prerequisite_courses
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM DIEUKIEN dk
        JOIN GIANGDAY gd1 ON dk.MAMH = gd1.MAMH
        JOIN GIANGDAY gd2 ON dk.MAMH_TRUOC = gd2.MAMH
        WHERE gd1.TUNGAY < gd2.DENNGAY
    )
    BEGIN
        ROLLBACK TRANSACTION
        THROW 50000, 'Môn học phải được học sau khi hoàn thành môn học tiên quyết.', 1
    END
END

--24.
GO
CREATE TRIGGER trg_check_teacher_assignment
ON GIANGDAY
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM GIANGDAY gd
        JOIN GIAOVIEN gv ON gd.MAGV = gv.MAGV
        JOIN MONHOC mh ON gd.MAMH = mh.MAMH
        WHERE gv.MAKHOA <> mh.MAKHOA
    )
    BEGIN
        ROLLBACK TRANSACTION
        THROW 50000, 'Giáo viên chỉ được phân công dạy những môn thuộc khoa phụ trách.', 1
    END
END