USE QuanLyBanHang_DB

--I--

--11.
GO
CREATE TRIGGER CHECK_NGDK_NGHD
ON HOADON
AFTER INSERT,UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM HOADON
		JOIN KHACHHANG
		ON HOADON.MAKH = KHACHHANG.MAKH
		WHERE HOADON.NGHD < KHACHHANG.NGDK AND HOADON.SOHD IN (SELECT SOHD FROM inserted)
	)
	BEGIN
		PRINT N'Ngày mua hàng (NGHD) không được nhỏ hơn ngày đăng ký thành viên (NGDK).'
		ROLLBACK TRANSACTION
	END
END

--12.
GO
CREATE TRIGGER CHECK_NGHD_NGVL
ON HOADON
AFTER INSERT, UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM HOADON
		JOIN NHANVIEN
		ON HOADON.MANV = NHANVIEN.MANV
		WHERE HOADON.NGHD < NHANVIEN.NGVL AND HOADON.SOHD IN (SELECT SOHD FROM inserted)
	)
	BEGIN
		PRINT N'Ngày bán hàng (NGHD) của một nhân viên phải lớn hơn hoặc bằng ngày nhân viên đó vào làm.'
		ROLLBACK TRANSACTION
	END
END


--III--

--41.
SELECT MONTH(NGHD), SUM(TRIGIA)
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC

--42.
SELECT TOP 1 SANPHAM.MASP, TENSP, SUM(SL) AS TONGSOLUONG
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE YEAR(HOADON.NGHD) = 2006
GROUP BY SANPHAM.MASP, SANPHAM.TENSP
ORDER BY TONGSOLUONG ASC

--43.
SELECT s1.NSX, s1.MASP, s1.TENSP, s1.GIA
FROM SANPHAM s1
WHERE s1.GIA = (
	SELECT MAX(s2.GIA)
	FROM SANPHAM s2
	WHERE s2.NSX = S1.NSX
	)

--44.
SELECT NSX
FROM SANPHAM
GROUP BY NSX
HAVING COUNT(DISTINCT GIA) >= 3