USE QuanLyBanHang_DB

SET DATEFORMAT DMY

--A--
--1.
ALTER TABLE SANPHAM ADD GHICHU varchar(20)

--2.
ALTER TABLE KHACHHANG ADD LOAIKH tinyint

--3.
ALTER TABLE SANPHAM ALTER COLUMN GHICHU varchar(100)

--4.
ALTER TABLE SANPHAM DROP COLUMN GHICHU

--5.
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_LOAIKH CHECK (LOAIKH IN (0, 1, 2)) -- 0 = 'Vang lai', 1 = 'Thuong xuyen', 2 = 'Vip'

--6.
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))

--7.
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIA CHECK (GIA >= 500)

--8.
ALTER TABLE CTHD
ADD CONSTRAINT CK_SL CHECK (SL >= 1)

--9.
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGDK_NGSINH CHECK (NGDK > NGSINH)

--B--
--1.
SELECT * INTO SANPHAM1 FROM SANPHAM;
SELECT * INTO KHACHHANG1 FROM KHACHHANG

--10.
UPDATE SANPHAM1
SET GIA = GIA * 1.05
WHERE NSX = 'Thai Lan'

--11.
UPDATE SANPHAM1
SET GIA = GIA * 0.95
WHERE NSX = 'Trung Quoc' AND GIA <= 10000

--12.
UPDATE KHACHHANG1
SET LOAIKH = 2  -- "Vip"
WHERE (NGDK < '01/01/2007' AND DOANHSO >= 10000000) OR (NGDK >= '01/01/2007' AND DOANHSO >= 2000000)

--C--
--13.
SELECT MASP, TENSP
FROM SANPHAM
WHERE NSX = 'Trung Quoc'

--14.
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN ('cay', 'quyen')

--15.
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01'

--16.
SELECT MASP, TENSP
FROM SANPHAM
WHERE NSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000

--17.
SELECT MASP, TENSP
FROM SANPHAM
WHERE NSX IN ('Trung Quoc', 'Thai Lan') AND GIA BETWEEN 30000 AND 40000

--18.
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD IN ('01/01/2007', '02/01/2007')

--19.
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007
ORDER BY NGHD ASC, TRIGIA DESC

--20.
SELECT DISTINCT KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG
JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE NGHD = '01/01/2007'

--21.
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MANV = (SELECT MANV FROM NHANVIEN WHERE HOTEN = 'Nguyen Van B') AND NGHD = '28/10/2006'

--22.
SELECT DISTINCT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
JOIN CTHD ON SANPHAM.MASP = CTHD.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE MAKH = (SELECT MAKH FROM KHACHHANG WHERE HOTEN = 'Nguyen Van A') AND MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006

--23.
SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP IN ('BB01', 'BB02')