USE QuanLyGiaoVu_DB

SET DATEFORMAT DMY

--1.
ALTER TABLE HOCVIEN ADD GHICHU text
ALTER TABLE HOCVIEN ADD DIEMTB numeric(4,2)
ALTER TABLE HOCVIEN ADD XEPLOAI varchar(20)

--2.
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_MAHV
CHECK (LEN(MAHV) = 5 AND SUBSTRING(MAHV,1,3) LIKE '[A-Z][0-9][0-9]' AND SUBSTRING(MAHV,4,2) LIKE '[0-9][0-9]')

--3.
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GIOITINH
CHECK (GIOITINH IN ('Nam', 'Nu'))

--4.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM
CHECK (DIEM BETWEEN 0 AND 10)

--5.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM_KQUA
CHECK (((DIEM BETWEEN 5 AND 10) AND KQUA = 'Dat') OR (DIEM < 5 AND KQUA = 'Khong dat'))

--6.
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_LANTHI
CHECK (LANTHI <= 3)

--7.
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY
CHECK (HOCKY BETWEEN 1 AND 3)

--8.
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HOCVI
CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))

--9.
GO
CREATE TRIGGER KTRA_TRG_LOP ON LOP  
FOR INSERT, UPDATE					
AS
BEGIN
	DECLARE @TRGLOP char(5),		
			@MALOP1 char(3),		
			@MALOP2 char(3)			

	SELECT @TRGLOP = TRGLOP, @MALOP1 = MALOP FROM INSERTED  
															 
															
	
	SELECT @MALOP2 = MALOP FROM HOCVIEN WHERE MAHV = @TRGLOP 

	IF (@MALOP1 <> @MALOP2) 
	BEGIN
		PRINT N'Lớp trưởng của một lớp phải là học viên của lớp đó!' 
		ROLLBACK TRANSACTION										 
	END
END

--10.
GO
CREATE TRIGGER KTRA_TRGKHOA ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @TRGKHOA char(4), @MAKHOA varchar(4), @HOCVI varchar(10)

	SELECT @TRGKHOA = TRGKHOA, @MAKHOA = MAKHOA FROM INSERTED
	SELECT @HOCVI = HOCVI FROM GIAOVIEN WHERE MAGV = @TRGKHOA AND MAKHOA = @MAKHOA

	IF (@HOCVI NOT IN ('TS', 'PTS'))
	BEGIN
		PRINT N'Trưởng khoa phải là giáo viên thuộc khoa và có học vị “TS” hoặc “PTS”!'
		ROLLBACK TRANSACTION
	END
END

--11.
ALTER TABLE HOCVIEN
ADD CHECK (YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

--12.
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_TUGNAY_DENNGAY
CHECK (TUNGAY < DENNGAY)

--13.
ALTER TABLE GIAOVIEN
ADD CHECK(YEAR(GETDATE()) - YEAR(NGSINH) >= 22)

--14.
ALTER TABLE MONHOC
ADD CONSTRAINT CK_TCLT_TCTH
CHECK (ABS(TCLT - TCTH) <= 3 OR TCTH = 0)

--15.
GO 
CREATE TRIGGER CK_NGTHI ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @NGTHI smalldatetime, @DENNGAY smalldatetime, @MAHV char(5), @MAMH varchar(10)

	SELECT @NGTHI = NGTHI, @MAHV = MAHV, @MAMH = MAMH FROM INSERTED
	SELECT @DENNGAY = DENNGAY FROM GIANGDAY WHERE MAMH = @MAMH

	IF (@NGTHI < @DENNGAY)
	BEGIN
		PRINT N'  Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này!'
		ROLLBACK TRANSACTION
	END
END

--16.
GO
CREATE TRIGGER COUNT_MAMH ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MALOP char(3), @TONGSOMH int, @HOCKY int, @NAM int

	SELECT @MALOP = MALOP, @HOCKY = HOCKY, @NAM = NAM FROM INSERTED
	SELECT @TONGSOMH = COUNT(MAMH) FROM GIANGDAY WHERE MALOP = @MALOP AND HOCKY = @HOCKY AND NAM = @NAM

	IF (@TONGSOMH > 3)
	BEGIN
		PRINT N'Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn!'
		ROLLBACK TRANSACTION
	END
END

--17.
GO
CREATE TRIGGER KTRA_SISO ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SISO tinyint, @TONGSOHV tinyint, @MALOP char(3)

	SELECT @SISO = SISO, @MALOP = MALOP FROM INSERTED
	SELECT @TONGSOHV = COUNT(MAHV) FROM HOCVIEN WHERE MALOP = @MALOP

	IF (@TONGSOHV <> @SISO)
	BEGIN
		PRINT N'Sĩ số của một lớp bằng với số lượng học viên thuộc lớp đó!'
		ROLLBACK TRANSACTION
	END
END

--18.
--Kiểm tra MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau (“A”,”A”)
GO
CREATE TRIGGER KTRA_DIEUKIEN ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAMH varchar(10), @MAMH_TRUOC varchar(10)

	SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC FROM INSERTED

	IF (@MAMH = @MAMH_TRUOC)
	BEGIN
		PRINT N'MAMH và MAMH_TRUOC trong cùng một bộ không được giống nhau!'
		ROLLBACK TRANSACTION
	END
END

--Kiểm tra MAMH và MAMH_TRUOC không tồn tại hai bộ (“A”,”B”) và (“B”,”A”)
GO
CREATE TRIGGER KTRA_BOGIONGNHAU ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(SELECT * FROM DIEUKIEN DK, INSERTED I WHERE DK.MAMH = I.MAMH_TRUOC AND DK.MAMH_TRUOC = I.MAMH)
	BEGIN
		PRINT N'MAMH và MAMH_TRUOC không tồn tại hai bộ!'
		ROLLBACK TRANSACTION
	END
END

--19.
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)

--20.
UPDATE HOCVIEN
SET DIEMTB = (SELECT AVG(DIEM)
			  FROM (SELECT MAHV, MAMH, MAX(LANTHI) MAX_LANTHI 
					FROM KETQUATHI
					GROUP BY MAHV, MAMH) A, KETQUATHI B
			  WHERE A.MAHV = B.MAHV AND MAX_LANTHI = B.LANTHI
			  GROUP BY B.MAHV
			  HAVING B.MAHV = HOCVIEN.MAHV)

--21.
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
FROM KETQUATHI KQT JOIN HOCVIEN HV ON KQT.MAHV = HV.MAHV
WHERE DIEM < 5 AND LANTHI = 3

--22.

UPDATE HOCVIEN
SET XEPLOAI = 'XS'
WHERE DIEMTB >= 9

UPDATE HOCVIEN
SET XEPLOAI = 'G'
WHERE DIEMTB >= 8 AND DIEMTB < 9

UPDATE HOCVIEN
SET XEPLOAI = 'K'
WHERE DIEMTB >= 6.5 AND DIEMTB < 8

UPDATE HOCVIEN
SET XEPLOAI = 'TB'
WHERE DIEMTB >= 5 AND DIEMTB < 6.5

UPDATE HOCVIEN
SET XEPLOAI = 'Y'
WHERE DIEMTB < 5

--23.
SELECT HOCVIEN.MAHV, HO, TEN, NGSINH, LOP.MALOP
FROM LOP , HOCVIEN 
WHERE LOP.TRGLOP = HOCVIEN.MAHV

--24.
SELECT HOCVIEN.MAHV, HO, TEN, LANTHI, DIEM
FROM HOCVIEN JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE MAMH = 'CTRR' AND MALOP = 'K12'
ORDER BY TEN, HO ASC

--25.
SELECT HOCVIEN.MAHV, HO, TEN
FROM HOCVIEN JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE LANTHI = 1 AND KQUA = 'Dat'

--26.
SELECT HOCVIEN.MAHV, HO, TEN 
FROM HOCVIEN JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE MALOP = 'K11' AND LANTHI = 1 AND KQUA = 'Khong dat'

--27.
SELECT MONHOC.MAMH, TENMH
FROM MONHOC JOIN GIANGDAY ON MONHOC.MAMH = GIANGDAY.MAMH
			JOIN GIAOVIEN ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE HOTEN = 'Tran Tam Thanh' AND HOCKY = 1 AND NAM = 2006

--28.
SELECT MONHOC.MAMH, TENMH
FROM MONHOC JOIN GIANGDAY ON MONHOC.MAMH = GIANGDAY.MAMH
			JOIN LOP ON LOP.MAGVCN = GIANGDAY.MAGV
WHERE HOCKY = 1 AND NAM = 2006 AND LOP.MALOP = 'K11'

--29.
SELECT HO, TEN
FROM HOCVIEN JOIN LOP ON HOCVIEN.MAHV = LOP.TRGLOP
			 JOIN GIAOVIEN ON GIAOVIEN.MAGV = LOP.MAGVCN
			 JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
			 JOIN MONHOC ON GIANGDAY.MAMH = MONHOC.MAMH
WHERE HOTEN = 'Nguyen To Lan' AND TENMH = 'Co so du lieu'

--30.
SELECT MAMH_TRUOC
FROM DIEUKIEN JOIN MONHOC ON MONHOC.MAMH = DIEUKIEN.MAMH
WHERE TENMH = 'Co so du lieu'

--31.
SELECT HOTEN
FROM GIAOVIEN JOIN GIANGDAY ON GIAOVIEN.MAGV = GIANGDAY.MAGV
WHERE MALOP IN ('K11','K12') AND MAMH = 'CTRR' AND HOCKY = 1 AND NAM = 2006